---
- name: Base configuration
  hosts: all
  become: yes
  roles:
    - base

- name: Configure K3s master nodes
  hosts: masters
  become: yes
  roles:
    - k3s_master

- name: Configure K3s worker nodes
  hosts: workers
  become: yes
  roles:
    - k3s_worker

- name: Install Cilium (if enabled)
  hosts: masters
  become: yes
  roles:
    - { role: cilium, when: cilium_enabled | default(false) | bool }

- name: Configure Cilium BGP (if enabled)
  hosts: masters
  become: yes
  roles:
    - { role: cilium_bgp, when: cilium_bgp_enabled | default(false) | bool }
