# User configuration for K3s deployment

# SSH settings
ssh_user: "your-ssh-user"

# K3s settings
k3s_version: "v1.29.1+k3s1"

# Cilium settings
cilium_enabled: true  # Set to false to disable Cilium
cilium_bgp_enabled: false  # Set to true to enable BGP if supported

# API Server Load Balancer
# - If using multiple masters, set this to an external Load Balancer IP.
# - If empty, the first master node's IP will be used.
api_server_ip: ""

# BGP Settings (Only applies if BGP is enabled)
bgp_config:
  enabled: false  # Set to true to enable BGP
  cluster_asn: 65001  # ASN for the K3s cluster
  router_asn: 64512   # ASN for the upstream router
  peers:
    - ip: "192.168.10.1"   # IP of the upstream router
      asn: 64512           # ASN of the upstream router

# LoadBalancer IP Pool (Optional)
# - Define a custom pool of IPs for LoadBalancer services if using BGP.
# - If empty, Cilium will dynamically allocate IPs.
lb_ip_pool: 
  # - start: "192.168.10.240"
  #   stop: "192.168.10.249"

# Ingress Controller Configuration
ingress_controller:
  enabled: true  # Set to false to disable IngressController
  default: true  # Set this as the default ingress controller
  loadbalancerMode: shared  # Shared LoadBalancer for all Ingress resources
  service:
    annotations:
      io.cilium/lb-ipam-ips: "192.168.10.240"  # Assign IP from LoadBalancer pool

# Storage settings
storage_classes:
  longhorn:
    enabled: true
    default: true
    default_path: "/mnt/longhorn"

  nfs:
    enabled: true
    server: "192.168.10.100"
    path: "/mnt/storage"
    default: false

  local-path:
    enabled: true
    default: false

# ARR stack
deploy_media_stack: false  # Set to true to install Plex, Radarr, Sonarr, etc.

# Per-Service Toggle (More Customization)
deploy_plex: false
deploy_sonarr: false
deploy_radarr: false
deploy_bazarr: false
deploy_prowlarr: false
deploy_lidarr: false
deploy_overseerr: false
deploy_sabnzbd: false

# Base domain for media services i.e.. homelab.com = plex.homelab.com etc.
domain_name: "yourdomain.com"
