# User configuration for K3s deployment

# SSH settings
ssh_user: "your-ssh-user"

# K3s settings
k3s_version: "v1.29.1+k3s1"

# Cilium settings
cilium_enabled: true  # Set to false to disable Cilium
cilium_bgp_enabled: false  # Set to true to enable BGP if supported

# API Server Load Balancer
# - If using multiple masters, set this to an external Load Balancer IP.
# - If empty, the first master node's IP will be used.
api_server_ip: ""

# LoadBalancer IP Pool (Optional)
# - Define a custom pool of IPs for LoadBalancer services if using BGP.
# - If empty, Cilium will dynamically allocate IPs.
lb_ip_pool: 
  # - start: "192.168.1.240"
  #   stop: "192.168.1.249"

