---
- name: Get the latest Cilium CLI version
  shell: "curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt"
  register: cilium_cli_version
  changed_when: false

- name: Download Cilium CLI
  shell: |
    CLI_ARCH=amd64
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version.stdout }}/cilium-linux-${CLI_ARCH}.tar.gz
    sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
    rm cilium-linux-${CLI_ARCH}.tar.gz
  args:
    executable: /bin/bash
  when: cilium_enabled | default(false) | bool

- name: Ensure Helm is installed
  package:
    name: helm
    state: present

- name: Add Cilium Helm repository
  shell: |
    helm repo add cilium https://helm.cilium.io
    helm repo update

- name: Determine API server IP
  set_fact:
    api_server_ip: >-
      {% if api_server_ip is defined and api_server_ip | length > 0 %}
        {{ api_server_ip }}
      {% elif groups['masters'] | length > 1 %}
        {{ hostvars[groups['masters'][0]]['ansible_host'] }}
      {% else %}
        {{ hostvars['master1']['ansible_host'] }}
      {% endif %}

- name: Install Cilium with explicit API server IP
  shell: |
    API_SERVER_IP={{ api_server_ip }}
    API_SERVER_PORT=6443
    cilium install \
      --set k8sServiceHost=${API_SERVER_IP} \
      --set k8sServicePort=${API_SERVER_PORT} \
      --set kubeProxyReplacement=true
  args:
    executable: /bin/bash
  when: cilium_enabled | default(false) | bool
