---
- name: Get the latest Cilium CLI version
  shell: "curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt"
  register: cilium_cli_version
  changed_when: false

- name: Download Cilium CLI
  shell: |
    CLI_ARCH=amd64
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version.stdout }}/cilium-linux-${CLI_ARCH}.tar.gz
    sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
    rm cilium-linux-${CLI_ARCH}.tar.gz
  args:
    executable: /bin/bash
  when: cilium_enabled | default(false) | bool

- name: Ensure Helm is installed
  package:
    name: helm
    state: present

- name: Add Cilium Helm repository
  shell: |
    helm repo add cilium https://helm.cilium.io
    helm repo update

- name: Determine API server IP
  set_fact:
    api_server_ip: >-
      {% if api_server_ip is defined and api_server_ip | length > 0 %}
        {{ api_server_ip }}
      {% elif groups['masters'] | length > 1 %}
        {{ hostvars[groups['masters'][0]]['ansible_host'] }}
      {% else %}
        {{ hostvars['master1']['ansible_host'] }}
      {% endif %}

- name: Install Cilium with explicit API server IP
  shell: |
    API_SERVER_IP={{ api_server_ip }}
    API_SERVER_PORT=6443
    cilium install \
      --set k8sServiceHost=${API_SERVER_IP} \
      --set k8sServicePort=${API_SERVER_PORT} \
      --set kubeProxyReplacement=true
  args:
    executable: /bin/bash
  when: cilium_enabled | default(false) | bool

# LoadBalancer Configuration
- name: Check if LoadBalancer IP Pool is defined
  set_fact:
    lb_pool_defined: "{{ lb_ip_pool is defined and lb_ip_pool.start is defined and lb_ip_pool.stop is defined }}"

- name: Render LoadBalancer IP Pool YAML (if defined)
  template:
    src: "ip-pool.yaml.j2"
    dest: "/tmp/ip-pool.yaml"
  when: lb_pool_defined

- name: Apply LoadBalancer IP Pool (if defined)
  shell: kubectl apply -f /tmp/ip-pool.yaml
  when: lb_pool_defined

  # IngressController Configuration
- name: Enable Cilium Ingress Controller
  shell: |
    kubectl apply -f - <<EOF
    apiVersion: cilium.io/v2alpha1
    kind: CiliumIngressController
    metadata:
      name: cilium-ingress
    spec:
      enabled: true
      default: true
      loadbalancerMode: shared
      service:
        annotations:
          io.cilium/lb-ipam-ips: "{{ ingress_ip | default('192.168.1.240') }}"
    EOF
  when: cilium_enabled | default(false) | bool