---
- name: Get the latest Cilium CLI version
  shell: "curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt"
  register: cilium_cli_version
  changed_when: false

- name: Download Cilium CLI
  shell: |
    CLI_ARCH=amd64
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version.stdout }}/cilium-linux-${CLI_ARCH}.tar.gz
    sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
    rm cilium-linux-${CLI_ARCH}.tar.gz
  args:
    executable: /bin/bash
  when: cilium_enabled | default(false) | bool

- name: Ensure Helm is installed
  package:
    name: helm
    state: present

- name: Add Cilium Helm repository
  shell: |
    helm repo add cilium https://helm.cilium.io
    helm repo update

- name: Install Cilium using Helm
  shell: |
    helm install cilium cilium/cilium \
      --namespace kube-system \
      --set kubeProxyReplacement=strict \
      --set ipam.mode=cluster-pool
  args:
    executable: /bin/bash
  when: cilium_enabled | default(false) | bool
