---
- name: Download K3s install script
  get_url:
    url: "https://get.k3s.io"
    dest: "/tmp/k3s_install.sh"
    mode: "0755"

- name: Install K3s master with Cilium (if enabled)
  shell: |
    /tmp/k3s_install.sh server \
      --flannel-backend=none \
      --disable-kube-proxy \
      --disable servicelb \
      --disable-network-policy \
      --disable traefik \
      --cluster-init
  args:
    creates: /etc/rancher/k3s/k3s.yaml
  when: cilium_enabled | default(false) | bool

- name: Install K3s master with default networking (if Cilium is disabled)
  shell: |
    /tmp/k3s_install.sh server \
      --cluster-init
  args:
    creates: /etc/rancher/k3s/k3s.yaml
  when: not (cilium_enabled | default(false) | bool)
